apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: university-system
type: Opaque
stringData:
  JWT_SECRET: "this is jwt secret"
  MONGODB_URI: "mongodb://mongodb-service:27017/university-system"
  STRIPE_SECRET_KEY: "123123"  # ← Wrapped in quotes to make it a string
