apiVersion: v1
kind: Service
metadata:
  name: mern-app-service
  namespace: university-system
spec:
  type: NodePort
  selector:
    app: mern-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
